##### 公共 配置 #######

#内置Tomcat容器配置
server:
  port: 8888
  servlet:
    #应用路径，配置应用路径，可方便进行反向代理
    context-path:
#    context-path: /baseadmin
#基础配置
spring:
  profiles:
    active: ${BASE_ADMIN:dev} #选择配置分支，先读取系统环境变量，如果没有则默认值为 dev
  application:
    name: base-admin

  #修改thymeleaf访问根路径
  thymeleaf:
    prefix: classpath:/view/

  #mvc接收参数时对日期进行格式化
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  #jackson对响应回去的日期参数进行格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #打印SQL
  jpa:
    show-sql: true

#是否需要输入验证码
captcha:
  enable: false

---
##### dev 配置 #######
spring:
  profiles: dev

  #数据库配置
  datasource:
    url: jdbc:mysql://192.168.50.130:3306/applecheck?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: false



#API接口地址
service:
  api_key: HENSON56743CHAUU

  service101:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=101&imei=PUT_YOUR_IMEI_HERE
  service102:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=102&imei=PUT_YOUR_IMEI_HERE
  service103:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=103&imei=PUT_YOUR_IMEI_HERE
  service104:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=104&imei=PUT_YOUR_IMEI_HERE
  service106:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=106&imei=PUT_YOUR_IMEI_HERE
  service107:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=107&imei=PUT_YOUR_IMEI_HERE
  service108:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=108&imei=PUT_YOUR_IMEI_HERE
  service109:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=109&imei=PUT_YOUR_IMEI_HERE
  service110:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=110&imei=PUT_YOUR_IMEI_HERE
  service111:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=111&imei=PUT_YOUR_IMEI_HERE
  service112:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=112&imei=PUT_YOUR_IMEI_HERE
  service113:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=113&imei=PUT_YOUR_IMEI_HERE
  service114:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=114&imei=PUT_YOUR_IMEI_HERE
  service115:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=115&imei=PUT_YOUR_IMEI_HERE
  service116:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=116&imei=PUT_YOUR_IMEI_HERE
  service117:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=117&imei=PUT_YOUR_IMEI_HERE
  service119:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=119&imei=PUT_YOUR_IMEI_HERE
  service121:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=121&imei=PUT_YOUR_IMEI_HERE
  service122:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=122&imei=PUT_YOUR_IMEI_HERE
  service124:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=124&imei=PUT_YOUR_IMEI_HERE
  service125:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=125&imei=PUT_YOUR_IMEI_HERE
  service127:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=127&imei=PUT_YOUR_IMEI_HERE
  service132:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=132&imei=PUT_YOUR_IMEI_HERE
  service133:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=133&imei=PUT_YOUR_IMEI_HERE
  service134:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=134&imei=PUT_YOUR_IMEI_HERE
  service135:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=135&imei=PUT_YOUR_IMEI_HERE
  service136:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=136&imei=PUT_YOUR_IMEI_HERE
  service137:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=137&imei=PUT_YOUR_IMEI_HERE
  service138:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=138&imei=PUT_YOUR_IMEI_HERE
  service139:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=139&imei=PUT_YOUR_IMEI_HERE
  service140:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=140&imei=PUT_YOUR_IMEI_HERE
  service141:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=141&imei=PUT_YOUR_IMEI_HERE
  service142:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=142&imei=PUT_YOUR_IMEI_HERE
  service143:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=143&imei=PUT_YOUR_IMEI_HERE
  service144:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=144&imei=PUT_YOUR_IMEI_HERE
  service145:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=145&imei=PUT_YOUR_IMEI_HERE
  service146:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=146&imei=PUT_YOUR_IMEI_HERE
  service147:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=147&imei=PUT_YOUR_IMEI_HERE
  service148:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=148&imei=PUT_YOUR_IMEI_HERE
  service149:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=149&imei=PUT_YOUR_IMEI_HERE
  service150:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=150&imei=PUT_YOUR_IMEI_HERE
  service151:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=151&imei=PUT_YOUR_IMEI_HERE
  service152:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=152&imei=PUT_YOUR_IMEI_HERE
  service153:
    api_link: http://applecheck.info/api_processor.php?api_key=PUT_YOUR_API_KEY_HERE&service_id=153&imei=PUT_YOUR_IMEI_HERE

---
##### prod 配置 #######
spring:
  profiles: prod

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: true
